[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 5173
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true